"use strict";
// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — provider registry.
// One concrete provider instance per declared `model`. Resolved by id.
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MODELS = void 0;
exports.getModel = getModel;
exports.listModelNames = listModelNames;
exports.resolveProvider = resolveProvider;
const openai_compat_1 = __importDefault(require("./openai_compat"));
const registry_1 = require("./registry");
// Substitute ${ENV_VAR} placeholders in declared values with runtime env vars.
function _sub(s) {
    return s.replace(/\$\{(\w+)\}/g, (_, k) => process.env[k] || '');
}
// Lazy-initialize providers since env vars may load after module init.
let _models = null;
function _buildModels() {
    const baseUrl = _sub("${SMALLCODE_BASE_URL}") || "http://localhost:1234/v1";
    const modelName = _sub("${SMALLCODE_MODEL}") || "default";
    const strongModel = _sub("${SMALLCODE_MODEL_STRONG}") || modelName;
    return {
        "MediumCoder": {
            name: "MediumCoder",
            modelName: strongModel,
            provider: new openai_compat_1.default(baseUrl),
            contextWindow: 32000,
            maxOutput: 8192,
            temperature: 0.1,
            topP: null,
            stop: [],
            costClass: "medium",
            latencyClass: "medium",
        },
        "SmallCoder": {
            name: "SmallCoder",
            modelName,
            provider: new openai_compat_1.default(baseUrl),
            contextWindow: 32000,
            maxOutput: 4096,
            temperature: 0.1,
            topP: null,
            stop: [],
            costClass: "small",
            latencyClass: "medium",
        },
        "TinyClassifier": {
            name: "TinyClassifier",
            modelName,
            provider: new openai_compat_1.default(baseUrl),
            contextWindow: 8192,
            maxOutput: 64,
            temperature: 0,
            topP: null,
            stop: [],
            costClass: "tiny",
            latencyClass: "fast",
        },
    };
}
exports.MODELS = new Proxy({}, {
    get(_, key) {
        if (!_models)
            _models = _buildModels();
        return _models[key];
    },
    ownKeys() {
        if (!_models)
            _models = _buildModels();
        return Object.keys(_models);
    },
    getOwnPropertyDescriptor(_, key) {
        if (!_models)
            _models = _buildModels();
        return _models[key] ? { configurable: true, enumerable: true, value: _models[key] } : undefined;
    },
});
function getModel(name) {
    if (!_models)
        _models = _buildModels();
    const e = _models[name];
    if (!e)
        throw new Error(`Unknown model: ${name}`);
    return e;
}
function listModelNames() {
    if (!_models)
        _models = _buildModels();
    return Object.keys(_models).sort();
}
/**
 * Resolve a provider by name. Checks the plugin registry first;
 * falls back to creating a default OpenAICompatProvider with the
 * configured baseUrl.
 *
 * IMPORTANT: Do NOT register the fallback into providerRegistry here.
 * resolveProvider() is a lookup, not a mutation. Registering the fallback
 * would pollute the registry with an unintended entry under whatever name
 * was passed in, causing later resolveProvider() calls to short-circuit
 * to the plugin path and bypass the real OpenAI-compat fetch.
 */
function resolveProvider(name) {
    const fromRegistry = registry_1.providerRegistry.get(name);
    if (fromRegistry)
        return fromRegistry;
    const baseUrl = _sub("${SMALLCODE_BASE_URL}") || "http://localhost:1234/v1";
    return new openai_compat_1.default(baseUrl);
}
