// Generated by MarrowScript compiler. DO NOT EDIT.
// Cognition Layer Phase 2 — provider registry.
// One concrete provider instance per declared `model`. Resolved by id.

import type { IModelProvider } from "./types";
import OpenAICompatProvider from "./openai_compat";
import { providerRegistry } from "./registry";

// Substitute ${ENV_VAR} placeholders in declared values with runtime env vars.
function _sub(s: string): string {
  return s.replace(/\$\{(\w+)\}/g, (_, k) => process.env[k] || '');
}

export interface ModelEntry {
  /** Declared model name (e.g. "TinyClassifier"). */
  name: string;
  /** Provider-specific identifier (the `name:` field of the .marrow `model` decl). */
  modelName: string;
  provider: IModelProvider;
  contextWindow: number;
  maxOutput: number;
  temperature: number;
  topP: number | null;
  stop: string[];
  costClass: "tiny" | "small" | "medium" | "large";
  latencyClass: "fast" | "medium" | "slow";
}

// Lazy-initialize providers since env vars may load after module init.
let _models: Record<string, ModelEntry> | null = null;

function _buildModels(): Record<string, ModelEntry> {
  const baseUrl = _sub("${SMALLCODE_BASE_URL}") || "http://localhost:1234/v1";
  const modelName = _sub("${SMALLCODE_MODEL}") || "default";
  const strongModel = _sub("${SMALLCODE_MODEL_STRONG}") || modelName;

  return {
    "MediumCoder": {
      name: "MediumCoder",
      modelName: strongModel,
      provider: new OpenAICompatProvider(baseUrl),
      contextWindow: 32000,
      maxOutput: 8192,
      temperature: 0.1,
      topP: null,
      stop: [],
      costClass: "medium",
      latencyClass: "medium",
    },
    "SmallCoder": {
      name: "SmallCoder",
      modelName,
      provider: new OpenAICompatProvider(baseUrl),
      contextWindow: 32000,
      maxOutput: 4096,
      temperature: 0.1,
      topP: null,
      stop: [],
      costClass: "small",
      latencyClass: "medium",
    },
    "TinyClassifier": {
      name: "TinyClassifier",
      modelName,
      provider: new OpenAICompatProvider(baseUrl),
      contextWindow: 8192,
      maxOutput: 64,
      temperature: 0,
      topP: null,
      stop: [],
      costClass: "tiny",
      latencyClass: "fast",
    },
  };
}

export const MODELS: Record<string, ModelEntry> = new Proxy({}, {
  get(_, key: string) {
    if (!_models) _models = _buildModels();
    return _models[key];
  },
  ownKeys() {
    if (!_models) _models = _buildModels();
    return Object.keys(_models);
  },
  getOwnPropertyDescriptor(_, key: string) {
    if (!_models) _models = _buildModels();
    return _models[key] ? { configurable: true, enumerable: true, value: _models[key] } : undefined;
  },
}) as Record<string, ModelEntry>;

export function getModel(name: string): ModelEntry {
  if (!_models) _models = _buildModels();
  const e = _models[name];
  if (!e) throw new Error(`Unknown model: ${name}`);
  return e;
}

export function listModelNames(): string[] {
  if (!_models) _models = _buildModels();
  return Object.keys(_models).sort();
}

/**
 * Resolve a provider by name. Checks the plugin registry first;
 * falls back to creating a default OpenAICompatProvider with the
 * configured baseUrl.
 *
 * IMPORTANT: Do NOT register the fallback into providerRegistry here.
 * resolveProvider() is a lookup, not a mutation. Registering the fallback
 * would pollute the registry with an unintended entry under whatever name
 * was passed in, causing later resolveProvider() calls to short-circuit
 * to the plugin path and bypass the real OpenAI-compat fetch.
 */
export function resolveProvider(name: string): IModelProvider {
  const fromRegistry = providerRegistry.get(name);
  if (fromRegistry) return fromRegistry;
  const baseUrl = _sub("${SMALLCODE_BASE_URL}") || "http://localhost:1234/v1";
  return new OpenAICompatProvider(baseUrl);
}
