// @ts-nocheck
// ═══════════════════════════════════════════════════════════════════════════════
// COMPILED FROM: marrow/tool_router.marrow
// Generated by MarrowScript compiler — deterministic tool category classifier
// Zero LLM calls, zero tokens, zero latency
// ═══════════════════════════════════════════════════════════════════════════════

'use strict';

/**
 * Category signal definitions.
 * Each category has weighted regex patterns that contribute to a score.
 * Negative weights act as anti-signals (reduce category score).
 */
const CATEGORIES = {
  read: {
    weight: 1.0,
    minConfidence: 0.4,
    signals: [
      { re: /\b(read|show|cat|display|print|view|open|look\s+at|check|see|inspect)\b/i, w: 3.0 },
      { re: /\b(what'?s\s+in|what\s+is\s+in|contents?\s+of|what\s+files|list\s+files|files\s+in|what'?s?\s+in)\b/i, w: 3.0 },
      // review/analyze/examine are read+write actions that need file tools
      { re: /\b(review|analyze|analyse|examine|audit|look\s+over|go\s+over)\b/i, w: 3.0 },
      { re: /\b(file|\.\w{1,4})\b/i, w: 1.5 },
      { re: /\b(fix|change|update|modify|add|remove|delete|create|write)\b/i, w: -2.0 },
      { re: /\b(run|execute|test|build|install)\b/i, w: -1.5 },
    ],
  },
  write: {
    weight: 1.0,
    minConfidence: 0.3,
    signals: [
      { re: /\b(fix|change|update|modify|edit|refactor|rename|replace|patch)\b/i, w: 3.0 },
      { re: /\b(add|insert|append|prepend|implement|create|write|make)\b/i, w: 2.5 },
      { re: /\b(remove|delete|strip|clean\s*up|drop)\b/i, w: 2.0 },
      { re: /\b(bug|error|typo|issue|broken|wrong|incorrect|failing|fail|crash)\b/i, w: 2.0 },
      { re: /\b(file|function|class|method|variable|import|export)\b/i, w: 1.0 },
      { re: /\b(explain|what|why|how\s+does|tell\s+me)\b/i, w: -1.5 },
      { re: /\b(search|find|grep|look\s+for)\b/i, w: -1.5 },
    ],
  },
  search: {
    weight: 1.0,
    minConfidence: 0.4,
    signals: [
      { re: /\b(find|search|grep|look\s+for|locate|where\s+is|where\s+are)\b/i, w: 3.0 },
      { re: /\b(all\s+uses?\s+of|all\s+references?|who\s+calls?|who\s+uses?|imports?\s+of)\b/i, w: 3.0 },
      { re: /\b(pattern|regex|match|occurrences?)\b/i, w: 2.0 },
      { re: /\b(across|everywhere|all\s+files|codebase|project)\b/i, w: 1.5 },
      { re: /\b(fix|change|update|create|write)\b/i, w: -2.0 },
    ],
  },
  run: {
    weight: 1.0,
    minConfidence: 0.15,
    signals: [
      { re: /\b(run|execute|start|launch|invoke)\b/i, w: 3.0 },
      { re: /\b(tests?|specs?|jest|pytest|mocha|vitest)\b/i, w: 3.0 },
      { re: /\b(build|compile|make|bundle|webpack|tsc|cargo)\b/i, w: 2.5 },
      { re: /\b(install|npm|pip|yarn|pnpm|apt|brew)\b/i, w: 2.5 },
      { re: /\b(lint|format|prettier|eslint|black|ruff)\b/i, w: 2.0 },
      { re: /\b(git|commit|push|pull|merge|branch|checkout|diff|status)\b/i, w: 2.0 },
      { re: /\b(deploy|docker|k8s|kubernetes|terraform)\b/i, w: 2.0 },
      { re: /\b(explain|what|why|how\s+does)\b/i, w: -1.5 },
    ],
  },
  plan: {
    weight: 1.0,
    minConfidence: 0.5,
    signals: [
      { re: /\b(implement|build|create|design|architect)\b/i, w: 2.0 },
      { re: /\b(full|complete|entire|whole|end.to.end|e2e)\b/i, w: 2.5 },
      { re: /\b(system|module|feature|service|api|app|application)\b/i, w: 1.5 },
      { re: /\b(step\s+by\s+step|plan|break\s+down|decompose|how\s+should\s+i)\b/i, w: 3.0 },
      { re: /\b(multiple\s+files|several\s+files|across\s+files|refactor\s+all)\b/i, w: 2.0 },
      { re: /\b(show|read|display|cat)\b/i, w: -2.0 },
    ],
  },
  code_intel: {
    weight: 1.0,
    minConfidence: 0.4,
    signals: [
      { re: /\b(how\s+does\s+\w+\s+work|how\s+is\s+\w+\s+implemented)\b/i, w: 3.5 },
      { re: /\b(what\s+calls?|who\s+calls?|callers?\s+of)\b/i, w: 3.5 },
      { re: /\b(inheritance|extends|subclass|parent\s+class|class\s+hierarchy)\b/i, w: 3.0 },
      { re: /\b(what\s+does\s+\w+\s+call|dependencies\s+of|call\s+graph|call\s+chain)\b/i, w: 3.0 },
      { re: /\b(explain\s+(symbol|function|class|method)|where\s+is\s+\w+\s+defined)\b/i, w: 2.5 },
      { re: /\b(trace|flow|data\s+flow|control\s+flow)\b/i, w: 2.0 },
      { re: /\b(fix|change|update|create|write|delete)\b/i, w: -2.0 },
      { re: /\b(run|execute|test|build)\b/i, w: -1.5 },
    ],
  },
  web: {
    weight: 1.0,
    minConfidence: 0.5,
    signals: [
      { re: /\b(search\s+the\s+web|google|look\s+up\s+online|internet)\b/i, w: 3.0 },
      { re: /\b(latest\s+version|current\s+version|newest|recent)\b/i, w: 2.0 },
      { re: /\b(documentation|docs|api\s+reference|npm\s+page|pypi)\b/i, w: 2.0 },
      { re: /\b(url|website|link|https?:\/\/)\b/i, w: 2.5 },
      { re: /\b(download|fetch\s+from|get\s+from)\b/i, w: 1.5 },
    ],
  },
  respond: {
    weight: 0.8,
    minConfidence: 0.3,
    signals: [
      { re: /\b(explain|what\s+is|what\s+are|what\s+does|how\s+does|how\s+do|tell\s+me|describe)\b/i, w: 3.0 },
      { re: /\b(why\s+is|why\s+does|why\s+do|why\s+did|why\s+doesn't|why\s+won't)\b/i, w: 1.5 },
      { re: /\b(difference\s+between|compare|vs|versus)\b/i, w: 2.5 },
      { re: /\b(help|guide|tutorial|example|show\s+me\s+how)\b/i, w: 2.0 },
      { re: /\b(opinion|think|recommend|suggest|best\s+practice)\b/i, w: 2.0 },
      { re: /\b(thanks|thank\s+you|ok|sure|yes|no|got\s+it)\b/i, w: 3.0 },
      // Reduce score for anything that implies accessing files
      { re: /\b(failing|failed|broken|crash|error|bug|wrong)\b/i, w: -2.0 },
      { re: /\b(review|check|look\s+at|analyze|analyse|read|show|examine|audit)\b/i, w: -3.0 },
      { re: /\b(file|code|function|class|module|script|demo|mode)\b/i, w: -1.5 },
    ],
  },
};

// Priority order for tie-breaking (prefer action over observation)
const PRIORITY = ['write', 'run', 'code_intel', 'search', 'plan', 'read', 'web', 'respond'];

// Policy constants
const SHORT_MSG_THRESHOLD = 10;
const LONG_MSG_THRESHOLD = 200;
const FALLBACK = 'read'; // When nothing matches confidently, default to read (gives file tools).
                         // 'respond' was the old default but it injects ZERO tools, causing the
                         // model to give up and ask the user for files manually instead of reading them.
const SHORT_MSG_DEFAULT = 'respond';

/**
 * Score a message against a single category.
 * @param {string} message
 * @param {object} category
 * @returns {number} raw score (can be negative)
 */
function scoreCategory(message, category) {
  let score = 0;
  for (const signal of category.signals) {
    if (signal.re.test(message)) {
      score += signal.w;
    }
  }
  return score * category.weight;
}

/**
 * Classify a user message into a tool category.
 * Pure deterministic — no LLM, no network, no randomness.
 *
 * @param {string} message - User input
 * @returns {{ category: string, confidence: number, scores: Record<string, number> }}
 */
function classifyToolCategory(message) {
  if (!message || typeof message !== 'string') {
    return { category: FALLBACK, confidence: 0, scores: {} };
  }

  const trimmed = message.trim();

  // Short message fast path (greetings, acks)
  // Only treat as greeting if it's actually short AND doesn't contain action words
  if (trimmed.length <= SHORT_MSG_THRESHOLD && !/\b(run|fix|read|show|find|build|test|git|npm|pip|go|cd|ls|rm|mv|cp)\b/i.test(trimmed)) {
    return { category: SHORT_MSG_DEFAULT, confidence: 1.0, scores: { respond: 1.0 } };
  }

  // Score all categories
  const scores = {};
  let maxScore = -Infinity;
  let maxCategory = FALLBACK;

  for (const [name, cat] of Object.entries(CATEGORIES)) {
    let score = scoreCategory(trimmed, cat);

    // Long message boost for plan category
    if (name === 'plan' && trimmed.length > LONG_MSG_THRESHOLD) {
      score += 2.0;
    }

    scores[name] = score;

    if (score > maxScore) {
      maxScore = score;
      maxCategory = name;
    } else if (score === maxScore) {
      // Tie-break by priority order
      if (PRIORITY.indexOf(name) < PRIORITY.indexOf(maxCategory)) {
        maxCategory = name;
      }
    }
  }

  // Confidence: based on margin between top score and second-best
  // A single strong signal match (3.0) is enough if nothing else scores higher
  const sortedScores = Object.entries(scores).sort((a, b) => b[1] - a[1]);
  const topScore = sortedScores[0][1];
  const secondScore = sortedScores.length > 1 ? sortedScores[1][1] : 0;
  const margin = topScore - Math.max(0, secondScore);
  // Confidence = how dominant the winner is (clamped 0-1)
  // Score of 3.0 with 0 second → confidence = 1.0
  // Score of 3.0 with 2.5 second → confidence = 0.17
  const confidence = topScore > 0 ? Math.min(1.0, margin / Math.max(topScore, 3.0)) : 0;

  // Check if winner has any positive score at all
  if (topScore <= 0) {
    return { category: FALLBACK, confidence: 0, scores };
  }

  // If confidence is very low (near-tie), use priority order
  if (confidence < 0.1 && sortedScores.length > 1) {
    // Near tie — pick by priority
    const tiedCats = sortedScores.filter(([_, s]) => s >= topScore - 0.5).map(([c]) => c);
    for (const p of PRIORITY) {
      if (tiedCats.includes(p)) return { category: p, confidence, scores };
    }
  }

  return { category: maxCategory, confidence, scores };
}

/**
 * Get the tool schemas that should be injected for a given category.
 * Used by 2-stage routing: classify first, then inject only relevant tool defs.
 *
 * @param {string} category
 * @returns {string[]} tool names to include in the prompt
 */
function getToolsForCategory(category) {
  switch (category) {
    case 'code_intel':
      return ['graph_search', 'explain_symbol', 'read_file', 'find_files', 'search', 'hybrid_search'];
    case 'read':
      return ['read_file', 'list_projects', 'graph_search', 'find_files', 'find_and_read'];
    case 'write':
      return ['read_file', 'write_file', 'patch', 'bash', 'read_and_patch', 'create_and_run'];
    case 'search':
      return ['search', 'find_files', 'graph_search', 'read_file', 'explain_symbol', 'search_and_read', 'hybrid_search'];
    case 'run':
      return ['bash', 'run', 'read_file'];
    case 'plan':
      return ['read_file', 'write_file', 'patch', 'bash', 'search', 'find_files', 'graph_search', 'memory_load', 'memory_remember', 'bone_compile', 'bone_check', 'read_and_patch', 'create_and_run', 'find_and_read', 'search_and_read'];
    case 'web':
      return ['web_search', 'web_fetch', 'read_file'];
    case 'respond':
      return []; // No tools needed for pure responses
    default:
      return ['read_file', 'write_file', 'patch', 'bash', 'search'];
  }
}

/**
 * Check if a category needs tools at all.
 * If false, skip tool injection entirely (saves ~800 prompt tokens).
 */
function categoryNeedsTools(category) {
  return category !== 'respond';
}

module.exports = {
  classifyToolCategory,
  getToolsForCategory,
  categoryNeedsTools,
  CATEGORIES,
  PRIORITY,
};
